Feat/auth
Mathmate-il/Mathmate-server pull request #14
Opened 2023-01-05 21:45 UTC by AmitGit217

2023-01-08 22:02 UTC, origranot commented on src/abstractClasses/AbstractDto.ts
> +}
Why do we need this?

We can use PartialTypes from nest.

2023-01-08 22:05 UTC, origranot commented on src/prisma/prisma.service.ts
> +}
Why do we need this?

We can use Prisma with Nest according to their docs.
https://docs.nestjs.com/recipes/prisma#use-prisma-client-in-your-nestjs-services

2023-01-08 22:11 UTC, origranot requested changes
Hey @AmitGit217,

I did a short overview at this code, I think you should consider my changes.
I didn't check and get into Google auth and etc..

2023-01-08 22:11 UTC, origranot commented on src/app.module.ts
> +    PrismaModule,
We don't need a module for Prisma.
we can use only a service.

2023-01-08 22:11 UTC, origranot commented on src/auth/auth.controller.ts
> +    return await this.authService.signUp(oAuthToken);
Should be signIn instead of signUp?

```suggestion
    return await this.authService.signIn(oAuthToken);

2023-01-08 22:11 UTC, origranot commented on src/auth/auth.controller.ts
> +  async signUp(@Body('token') oAuthToken: string): Promise<unknown> {
I think we should use token as header and not inside the body.

2023-01-08 22:11 UTC, origranot commented on src/auth/auth.service.ts
> +      return this.signToken(userExist.id);
If the email is already taken we want to raise an exception.
According to this code, you can bypass the login.

2023-01-08 22:11 UTC, origranot commented on src/auth/dto/AuthDto.ts
> +export class AuthDto extends AbstractDto {
Use PartialTypes:

https://docs.nestjs.com/openapi/mapped-types

2023-01-08 22:11 UTC, origranot commented on src/prisma/prisma.module.ts
> +export class PrismaModule {}
We don't need a prisma module

2023-01-08 22:11 UTC, origranot commented on src/main.ts
> +  await app.listen(3001);
Maybe take port dynamically from config file?

2023-01-08 22:28 UTC, AmitGit217 commented
Thank you @origranot, I will look into my code and change the relevant suggestions. 
We really appreciate your time and effort in this code review!!!

2023-01-09 09:27 UTC, AmitGit217 commented on src/prisma/prisma.service.ts
> +}
What is the difference between the two approaches? 
I see that the PrismaModule is really unneeded but the Prisma service class is our tool to work with.

What do you think about creating for example UserRepository that will include all the common tasks of Prisma for the UserService to achieve a level of abstraction?

2023-01-09 09:30 UTC, AmitGit217 commented on src/abstractClasses/AbstractDto.ts
> +}
I used it to assign data from the response of google-auth because we receive from the FE only the token and it is not of type AuthDto ({email, name} both validated).

`
const { email, name } = await this.googleAuth(oAuthToken);
const user = new AuthDto({email, name})

`

2023-01-09 10:55 UTC, AmitGit217 commented on src/prisma/prisma.service.ts
> +}
https://www.codewithvlad.com/blog/how-to-use-prisma-in-nestjs

2023-01-09 11:35 UTC, origranot commented on src/prisma/prisma.service.ts
> +}
I would not create a service for each Entity.

2023-01-09 16:40 UTC, AmitGit217 commented on src/app.module.ts
> +    PrismaModule,
https://www.prisma.io/blog/nestjs-prisma-rest-api-7D056s1BmOL0

In any article that I've seen they used Prisma module

2023-01-09 17:11 UTC, rivershertz approved these changes

2023-01-09 17:11 UTC, merged